### ISSUE TITLE
v3 roadmap

### ISSUE THREAD

**Issue by garronej** [garronej/evt#63]
- [ ] Get rid of the need to add the `$` when attaching with operator.
- [ ] Support for async operators ( other than with `"evt/asyncPipe"`).
- [ ] Create `SelfManaged` operators for more complex operation.
- [ ] `StatefulEvt`: Get rid of `evtDiff`, `evtChange`, `evtChangeDiff`, provide operators to polifill this behaviour. 
- [ ] Way (via an operator) to get from an `evt` a new instance that only `postAsyncOnceHandled`.
- [ ] Decide if pipe on statefull event should should internally call `evt.state = x` or `evt.post(x)`. (see comment, currently it calls post)  
- [ ] We should be able to create StatefullEvt where the initial state is only computer when accessed `Evt.create(()=> "initial state" )`
- [ ] ctx.evtDoneOrAborted() should be a StatefulEvt
